/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import aima.core.environment.wumpusworld.AgentPercept;
import aima.core.search.framework.SearchAgent;
import aima.core.search.framework.problem.*;
import aima.core.search.uninformed.BreadthFirstSearch;
import missionaries_cannibals.ActionFunctionMC;
import missionaries_cannibals.GoalTestMC;
import missionaries_cannibals.ResultFunctionMC;

public class App {
 

    public static void main(String[] args) {
        // start problem solution
        int[] initial_state= new int[3];

        Problem problem = new Problem(initial_state, new ActionFunctionMC(), new ResultFunctionMC(), new GoalTestMC(), null);
        try {
            SearchAgent agent =new SearchAgent(problem,new BreadthFirstSearch());
            // run search agent
            //agent.execute(new AgentPercept(false, false, false, false, false));
            System.out.println(agent.getActions());
            System.out.println(agent.isDone());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
}
